import "server-only";
import type { Project } from "../types";
import { CATEGORIES, slugify } from "../constants";

const orNone = (v?: string) => (v && v.trim() ? v.trim() : "_Not specified._");

function authorsLine(p: Project): string {
  if (!p.authors.length) return "_Not specified._";
  return p.authors
    .map((a) => {
      const orcid = a.orcid ? ` ([ORCID ${a.orcid}](https://orcid.org/${a.orcid}))` : "";
      return `- ${a.name}${orcid}`;
    })
    .join("\n");
}

function institutionsLine(p: Project): string {
  if (!p.institutions.length) return "_Not specified._";
  return p.institutions
    .map((i) => `- ${i.name}${i.department ? ` — ${i.department}` : ""}`)
    .join("\n");
}

function citation(p: Project, year: number): string {
  const names = p.authors.map((a) => a.name).join("; ") || "EASER contributors";
  const inst = p.institutions.map((i) => i.name).join(", ");
  return `${names} (${year}). *${p.title}*. EASER Research Repository${inst ? `, ${inst}` : ""}.`;
}

/** Publication-quality README built from project metadata (deterministic). */
export function buildProjectReadme(p: Project, publishedFileNames: string[]): string {
  const category = CATEGORIES.find((c) => c.value === p.category)?.label ?? p.category;
  const year = new Date(p.submittedAt || p.createdAt || Date.now()).getFullYear();
  const departments = p.institutions.filter((i) => i.department).map((i) => `${i.name}: ${i.department}`);
  const orcids = p.authors.filter((a) => a.orcid).map((a) => `${a.name}: ${a.orcid}`);
  const files = publishedFileNames.length
    ? publishedFileNames.map((f) => `- \`${f}\``).join("\n")
    : "_No files included._";

  return `# ${p.title}

> ${category} · EASER Research Repository

## Authors
${authorsLine(p)}

## Institutions
${institutionsLine(p)}

## Department
${departments.length ? departments.map((d) => `- ${d}`).join("\n") : "_Not specified._"}

## ORCID
${orcids.length ? orcids.map((o) => `- ${o}`).join("\n") : "_Not specified._"}

## Contact Information
${p.contactName || "_Not specified._"}${p.contactEmail ? ` — ${p.contactEmail}` : ""}

## Description
${orNone(p.description)}

## Purpose
${orNone(p.purpose)}

## Included Files
${files}

## Dependencies
${orNone(p.dependencies)}

## Requirements
${orNone(p.requirements)}

## Installation
${orNone(p.installation)}

## Execution
${orNone(p.execution)}

## Keywords
${p.keywords.length ? p.keywords.map((k) => `\`${k}\``).join(", ") : "_None._"}

## License
${p.license || "_Not specified._"}

## Citation
> ${citation(p, year)}

## Submission Date
${new Date(p.submittedAt || p.createdAt || Date.now()).toISOString().slice(0, 10)}

---
*Generated by the EASER Research Data Hub from researcher-provided metadata and reviewed by a project curator before publication.*
`;
}

/** Machine-readable companion written alongside the README. */
export function buildProjectMetadata(p: Project, publishedFileNames: string[]) {
  const year = new Date(p.submittedAt || p.createdAt || Date.now()).getFullYear();
  return {
    schema: "easer-project/1",
    id: p.id,
    title: p.title,
    slug: p.slug || slugify(p.title),
    category: p.category,
    description: p.description,
    purpose: p.purpose,
    authors: p.authors,
    institutions: p.institutions,
    contact: { name: p.contactName, email: p.contactEmail },
    keywords: p.keywords,
    license: p.license || null,
    relatedLinks: p.relatedLinks || [],
    files: publishedFileNames,
    technical: {
      dependencies: p.dependencies || null,
      requirements: p.requirements || null,
      installation: p.installation || null,
      execution: p.execution || null,
      inputFiles: p.inputFiles || null,
      outputFiles: p.outputFiles || null
    },
    year,
    submissionDate: new Date(p.submittedAt || p.createdAt || Date.now()).toISOString(),
    source: "easer-research-data-hub"
  };
}
