import "server-only";
import type { DocProvider, DocGenContext, DocResult } from "./provider";
import { CATEGORIES } from "../constants";

const orNone = (v?: string) => (v && v.trim() ? v.trim() : "_Not specified._");
const list = (items?: string[]) =>
  items && items.length ? items.map((i) => `\`${i}\``).join(", ") : "_None._";

// Deterministic, offline README generator. Always available — no API key.
// Produces a complete, well-structured draft that the curator can refine.
export class TemplateDocProvider implements DocProvider {
  readonly name = "template" as const;
  async generate(ctx: DocGenContext): Promise<DocResult> {
    const { submitter, metadata: m, files, repoPath } = ctx;
    const categoryLabel = CATEGORIES.find((c) => c.value === m.category)?.label ?? m.category;
    const fileList = files.length
      ? files.map((f) => `- \`${f.name}\` (${(f.size / 1024).toFixed(1)} KB)`).join("\n")
      : "_No files attached — see repository path._";

    const md = `# ${m.title}

> ${categoryLabel} · Contributed to the EASER research repository
> Repository path: \`${repoPath}\`

## Author
**${submitter.name}**${submitter.orcid ? ` ([ORCID](https://orcid.org/${submitter.orcid}))` : ""}

## Affiliation
${orNone(submitter.affiliation)}

## Description
${orNone(m.description)}

## Purpose
${orNone(m.purpose)}

## Dependencies
${orNone(m.dependencies)}

## Requirements
${orNone(m.requirements)}

## Installation
${orNone(m.installation)}

## Execution
${orNone(m.execution)}

## Input Files
${orNone(m.inputFiles)}

## Output Files
${orNone(m.outputFiles)}

## Included Files
${fileList}

## Keywords
${list(m.keywords)}

${m.license ? `## License\n${m.license}\n` : ""}${
      m.relatedLinks && m.relatedLinks.length
        ? `## Related Links\n${m.relatedLinks.map((l) => `- ${l}`).join("\n")}\n`
        : ""
    }## Notes
${orNone(m.notes)}

## Contact
${submitter.name} — ${submitter.email}

---
*This documentation was generated by the EASER Research Data Hub from researcher-provided metadata and reviewed by the project curator before publication.*
`;
    return { markdown: md, generatedBy: "template" };
  }
}
