"use client";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";
import { Card, Button, Badge, Textarea } from "@/components/ui";
import { Markdown } from "@/components/Markdown";
import { apiGet, apiPost, apiPatch } from "@/lib/client";
import type { Contribution } from "@/lib/types";

export default function ReviewPage() {
  const { id } = useParams<{ id: string }>();
  const router = useRouter();
  const [c, setC] = useState<Contribution | null>(null);
  const [draft, setDraft] = useState("");
  const [editing, setEditing] = useState(false);
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [rejectNote, setRejectNote] = useState("");

  async function load() {
    try {
      const data = await apiGet<Contribution>(`/api/contributions/${id}`, true);
      setC(data); setDraft(data.draft?.markdown || "");
    } catch (e: any) { setError(e.message); }
  }
  useEffect(() => { load(); /* eslint-disable-next-line */ }, [id]);

  async function act(fn: () => Promise<any>, tag: string) {
    setBusy(tag); setError("");
    try { await fn(); await load(); }
    catch (e: any) { setError(e.message); }
    finally { setBusy(""); }
  }

  if (error && !c) return <div className="mx-auto max-w-3xl px-4 py-12"><Card className="border-amber-200 bg-amber-50 p-4 text-amber-800">{error} — <Link className="underline" href="/admin">back</Link></Card></div>;
  if (!c) return <div className="mx-auto max-w-3xl px-4 py-12 text-stone-500">Loading…</div>;

  const m = c.metadata;
  return (
    <div className="mx-auto max-w-4xl px-4 py-10">
      <Link href="/admin" className="text-sm text-brand-600 hover:underline">← Back to dashboard</Link>
      <div className="mt-2 flex items-start justify-between">
        <h1 className="text-2xl font-bold text-stone-900">{m.title}</h1>
        <Badge color="blue">{c.status.replace("_", " ")}</Badge>
      </div>
      <p className="mt-1 text-sm text-stone-500">{c.submitter.name} · {c.submitter.affiliation} · {c.submitter.email}</p>

      {error && <Card className="mt-4 border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</Card>}

      {/* Metadata */}
      <Card className="mt-6 p-5">
        <h2 className="font-semibold text-stone-900">Submitted metadata</h2>
        <dl className="mt-3 grid gap-x-6 gap-y-2 text-sm sm:grid-cols-2">
          {([
            ["Category", m.category], ["Description", m.description], ["Purpose", m.purpose],
            ["Dependencies", m.dependencies], ["Requirements", m.requirements],
            ["Installation", m.installation], ["Execution", m.execution],
            ["Input files", m.inputFiles], ["Output files", m.outputFiles],
            ["Keywords", m.keywords?.join(", ")], ["License", m.license], ["Notes", m.notes]
          ] as [string, string | undefined][]).filter(([, v]) => v).map(([k, v]) => (
            <div key={k}><dt className="font-medium text-stone-500">{k}</dt><dd className="text-stone-800">{v}</dd></div>
          ))}
        </dl>
        {c.files.length > 0 && (
          <div className="mt-3 text-sm"><span className="font-medium text-stone-500">Files: </span>{c.files.map((f) => f.name).join(", ")}</div>
        )}
      </Card>

      {/* Documentation draft */}
      <Card className="mt-6 p-5">
        <div className="flex items-center justify-between">
          <h2 className="font-semibold text-stone-900">Documentation draft</h2>
          <div className="flex gap-2">
            <Button variant="secondary" disabled={busy === "gen"} onClick={() => act(() => apiPost(`/api/contributions/${id}/generate-docs`, {}, true), "gen")}>
              {busy === "gen" ? "Generating…" : c.draft ? "Regenerate" : "Generate draft"}
            </Button>
            {c.draft && <Button variant="ghost" onClick={() => setEditing(!editing)}>{editing ? "Preview" : "Edit"}</Button>}
          </div>
        </div>

        {!c.draft ? (
          <p className="mt-4 text-sm text-stone-500">No draft yet. Click “Generate draft” to create documentation from the metadata.</p>
        ) : editing ? (
          <div className="mt-4">
            <Textarea rows={20} value={draft} onChange={(e) => setDraft(e.target.value)} className="font-mono text-xs" />
            <Button className="mt-3" disabled={busy === "save"} onClick={() => act(() => apiPatch(`/api/contributions/${id}`, { draftMarkdown: draft }), "save")}>
              {busy === "save" ? "Saving…" : "Save edits"}
            </Button>
          </div>
        ) : (
          <div className="mt-4 rounded-lg border border-stone-100 bg-stone-50 p-4">
            <p className="mb-2 text-xs text-stone-400">Generated by {c.draft.generatedBy}{c.draft.edited ? " · edited" : ""}</p>
            <Markdown>{c.draft.markdown}</Markdown>
          </div>
        )}
      </Card>

      {/* Decision */}
      {!["published", "approved", "rejected"].includes(c.status) && (
        <Card className="mt-6 p-5">
          <h2 className="font-semibold text-stone-900">Decision</h2>
          <p className="mt-1 text-sm text-stone-500">Approving publishes to GitHub (the repository remains the source of truth). Nothing is committed without your approval.</p>
          <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:items-center">
            <Button disabled={!c.draft || busy === "approve"} onClick={() => act(() => apiPost(`/api/contributions/${id}/approve`, {}, true), "approve")}>
              {busy === "approve" ? "Publishing…" : "Approve & publish to GitHub"}
            </Button>
          </div>
          <div className="mt-4">
            <Textarea rows={2} placeholder="Reason for requesting changes (sent to contributor)…" value={rejectNote} onChange={(e) => setRejectNote(e.target.value)} />
            <Button variant="danger" className="mt-2" disabled={busy === "reject"} onClick={() => act(() => apiPost(`/api/contributions/${id}/reject`, { note: rejectNote }, true), "reject")}>
              {busy === "reject" ? "Sending…" : "Request changes / reject"}
            </Button>
          </div>
        </Card>
      )}

      {c.githubCommitUrl && (
        <Card className="mt-6 border-green-200 bg-green-50 p-4 text-sm text-green-800">
          Published to GitHub: <a className="underline" href={c.githubCommitUrl} target="_blank" rel="noreferrer">{c.githubCommitUrl}</a>
          {c.githubPrNumber ? ` (PR #${c.githubPrNumber})` : ""}
        </Card>
      )}

      {/* Audit trail */}
      <Card className="mt-6 p-5">
        <h2 className="font-semibold text-stone-900">Activity</h2>
        <ul className="mt-3 space-y-1 text-sm text-stone-600">
          {c.audit.map((a, i) => (
            <li key={i}><span className="text-stone-400">{new Date(a.at).toLocaleString()}</span> — <strong>{a.action}</strong> by {a.actor}{a.note ? ` (${a.note})` : ""}</li>
          ))}
        </ul>
      </Card>
    </div>
  );
}
